# Generated by Django 6.1 on 2026-08-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_usagelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usagelog',
            old_name='estimated_cost',
            new_name='estimated_cost_usd',
        ),
    ]
